drop table if exists entrada_informe;
drop table if exists informe_pericial;
drop table if exists trucada;
drop table if exists cita;
drop table if exists sinistre;
drop table if exists cobertura;
drop table if exists polissa;
drop table if exists client;
drop table if exists perit;