/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.infomila.ui;

import info.infomila.IComponentSGBD;
import info.infomila.IComponentSGBDException;
import info.infomila.model.Polissa;
import info.infomila.model.Sinistre;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mr. Robot
 */
public class FormulariSinistre extends javax.swing.JFrame {

    private JFrame parentFrame;
    private String[] tipusSinistres = new String[]{"FUITA_AIGUA", "ELECTRICITAT", "GAS", "ELECTRODOMESTIC", "ROBATORI", "HUMITAT"};
    private String[] estatSinistre = new String[]{"NOU", "ASSIGNAT", "TANCAT"};
    private IComponentSGBD dbConnector;
    /**
     * Creates new form FormulariSinistre
     */
    public FormulariSinistre(JFrame parent,IComponentSGBD dbConnector) {
        initComponents();
        this.parentFrame = parent;
        this.dbConnector = dbConnector;
        initComponentsCorrectly();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNumPolissaNou = new javax.swing.JTextField();
        jXDatePickerObertura = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerTancament = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerAssignacio = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcio = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chkbArxivat = new javax.swing.JCheckBox();
        cboxTipusSinistre = new javax.swing.JComboBox<>();
        cboxEstatSinistre = new javax.swing.JComboBox<>();
        btnDesarSinistre = new javax.swing.JButton();
        btnCancelarSinistre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Nou Sinistre");
        jLabel1.setToolTipText("");

        jLabel2.setText("Data Obertura");

        jLabel3.setText("Data Tancament");

        jLabel4.setText("Data Assignació");

        jLabel5.setText("Descripció");

        jLabel6.setText("Numero Polissa");

        tfNumPolissaNou.setBackground(new java.awt.Color(255, 102, 102));

        jXDatePickerObertura.setEnabled(false);

        taDescripcio.setBackground(new java.awt.Color(255, 102, 102));
        taDescripcio.setColumns(20);
        taDescripcio.setRows(5);
        jScrollPane1.setViewportView(taDescripcio);

        jLabel7.setText("Tipus Sinistre");

        jLabel8.setText("Estat Sinistre");

        jLabel9.setText("Arxivat");

        cboxTipusSinistre.setBackground(new java.awt.Color(255, 102, 102));
        cboxTipusSinistre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxEstatSinistre.setBackground(new java.awt.Color(255, 102, 102));
        cboxEstatSinistre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDesarSinistre.setText("Desar");
        btnDesarSinistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesarSinistreMouseClicked(evt);
            }
        });

        btnCancelarSinistre.setText("Cancelar");
        btnCancelarSinistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarSinistreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jXDatePickerAssignacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jXDatePickerTancament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(jXDatePickerObertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(tfNumPolissaNou, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxEstatSinistre, 0, 119, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxTipusSinistre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDesarSinistre)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkbArxivat)))
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarSinistre)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNumPolissaNou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cboxTipusSinistre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePickerObertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cboxEstatSinistre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkbArxivat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jXDatePickerTancament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jXDatePickerAssignacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesarSinistre)
                    .addComponent(btnCancelarSinistre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarSinistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarSinistreMouseClicked
        parentFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarSinistreMouseClicked

    private void btnDesarSinistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesarSinistreMouseClicked
       if(!tfNumPolissaNou.getText().isEmpty() && ! taDescripcio.getText().isEmpty()){ 
           Sinistre result = creaObjecteSinistre();
        ((UI) parentFrame).addSinistre(null);
        parentFrame.setEnabled(true);
        this.dispose();
       }else {
           JOptionPane.showMessageDialog(null, "Camps marcats en vermell OBLIGATORIS","ERROR",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnDesarSinistreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarSinistre;
    private javax.swing.JButton btnDesarSinistre;
    private javax.swing.JComboBox<String> cboxEstatSinistre;
    private javax.swing.JComboBox<String> cboxTipusSinistre;
    private javax.swing.JCheckBox chkbArxivat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAssignacio;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerObertura;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerTancament;
    private javax.swing.JTextArea taDescripcio;
    private javax.swing.JTextField tfNumPolissaNou;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCorrectly() {
        this.setVisible(true);
        this.setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        cboxTipusSinistre.setModel(new DefaultComboBoxModel(tipusSinistres));
        cboxEstatSinistre.setModel(new DefaultComboBoxModel(estatSinistre));
        jXDatePickerObertura.setDate(new Date());

    }

    private Sinistre creaObjecteSinistre() {
        try {
            Sinistre s = new Sinistre();
            
            Polissa p = dbConnector.getPolissaPerId(1);
        } catch (IComponentSGBDException ex) {
            JOptionPane.showMessageDialog(null, "Codi polissa inexistent","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
}
