/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.infomila.ui;

import info.infomila.IComponentSGBD;
import info.infomila.IComponentSGBDException;
import info.infomila.model.Sinistre;
import info.infomila.model.Trucada;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mr. Robot
 */
public class FormulariTrucada extends javax.swing.JFrame {

    private Sinistre sinistreTrucada;
    private JFrame parentFrame;
    private IComponentSGBD dbConnector;

    public FormulariTrucada(JFrame parentFrame, IComponentSGBD dbConnector, Sinistre sinistreTrucada) {
        initComponents();
        this.sinistreTrucada = sinistreTrucada;
        this.parentFrame = parentFrame;
        this.dbConnector = dbConnector;
        initComponentsExtra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXDatePickerTrucada = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        tfPersonaContacte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcio = new javax.swing.JTextArea();
        btnDesarTrucada = new javax.swing.JButton();
        btnCancelarTrucada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nova Trucada");

        jLabel2.setText("Data Trucada");

        jXDatePickerTrucada.setEnabled(false);

        jLabel3.setText("Persona Contacte");

        jLabel4.setText("Descripció");

        taDescripcio.setColumns(20);
        taDescripcio.setRows(5);
        jScrollPane1.setViewportView(taDescripcio);

        btnDesarTrucada.setText("Desar");
        btnDesarTrucada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesarTrucadaMouseClicked(evt);
            }
        });

        btnCancelarTrucada.setText("Cancelar");
        btnCancelarTrucada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarTrucadaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jXDatePickerTrucada, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(tfPersonaContacte)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesarTrucada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarTrucada)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePickerTrucada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPersonaContacte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTrucada)
                    .addComponent(btnDesarTrucada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesarTrucadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesarTrucadaMouseClicked
        Trucada t = new Trucada(jXDatePickerTrucada.getDate(), taDescripcio.getText(), tfPersonaContacte.getText());
        try {
            dbConnector.afegirTrucada(t, sinistreTrucada);
            System.out.println("Trucada inserida");
            obrirPopUp();
        } catch (IComponentSGBDException ex) {
            Logger.getLogger(FormulariTrucada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDesarTrucadaMouseClicked

    private void btnCancelarTrucadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarTrucadaMouseClicked
        parentFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarTrucadaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTrucada;
    private javax.swing.JButton btnDesarTrucada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerTrucada;
    private javax.swing.JTextArea taDescripcio;
    private javax.swing.JTextField tfPersonaContacte;
    // End of variables declaration//GEN-END:variables

    private void initComponentsExtra() {
        jXDatePickerTrucada.setDate(new Date());
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    private void obrirPopUp() {
        String[] options = new String[] {"OK"};
        JOptionPane.showOptionDialog(
                this,
                "Trucada Enregistrada",              
                "Completat",JOptionPane.PLAIN_MESSAGE,
                   JOptionPane.QUESTION_MESSAGE,
                   null,
                   options,
                   options[0]);      

        parentFrame.setEnabled(true);
        this.dispose();
    }
}
