/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.infomila.ui;

import info.infomila.IComponentSGBD;
import info.infomila.IComponentSGBDException;
import info.infomila.enums.ESTAT_SINISTRE;
import info.infomila.enums.TIPUS_SINISTRE;
import info.infomila.model.Perit;
import info.infomila.model.Polissa;
import info.infomila.model.Sinistre;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mr. Robot
 */
public class FormulariSinistre extends javax.swing.JFrame {

    private JFrame parentFrame;
    private String[] tipusSinistres = new String[]{"FUITA_AIGUA", "ELECTRICITAT", "GAS", "ELECTRODOMESTIC", "ROBATORI", "HUMITAT"};
    private String[] estatSinistre = new String[]{"NOU", "ASSIGNAT", "TANCAT"};
    private IComponentSGBD dbConnector;
    private List<Perit> perits = new ArrayList<>();
    private List<Polissa> polices = new ArrayList();
    private boolean tancat = false;

    /**
     * Creates new form FormulariSinistre
     */
    public FormulariSinistre(JFrame parent, IComponentSGBD dbConnector) {
        initComponents();
        this.parentFrame = parent;
        this.dbConnector = dbConnector;
        initComponentsCorrectly();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jXDatePickerObertura = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerTancament = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerAssignacio = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcio = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboxTipusSinistre = new javax.swing.JComboBox<>();
        cboxEstatSinistre = new javax.swing.JComboBox<>();
        btnDesarSinistre = new javax.swing.JButton();
        btnCancelarSinistre = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cboxPerits = new javax.swing.JComboBox<>();
        cboxPolices = new javax.swing.JComboBox<>();
        btnTancarObrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Nou Sinistre");
        jLabel1.setToolTipText("");

        jLabel2.setText("Data Obertura");

        jLabel3.setText("Data Tancament");

        jLabel4.setText("Data Assignació");

        jLabel5.setText("Descripció");

        jLabel6.setText("Numero Polissa");

        jXDatePickerObertura.setEnabled(false);

        taDescripcio.setBackground(new java.awt.Color(255, 102, 102));
        taDescripcio.setColumns(20);
        taDescripcio.setRows(5);
        jScrollPane1.setViewportView(taDescripcio);

        jLabel7.setText("Tipus Sinistre");

        jLabel8.setText("Estat Sinistre");

        cboxTipusSinistre.setBackground(new java.awt.Color(255, 102, 102));
        cboxTipusSinistre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxEstatSinistre.setBackground(new java.awt.Color(255, 102, 102));
        cboxEstatSinistre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxEstatSinistre.setEnabled(false);

        btnDesarSinistre.setText("Desar");
        btnDesarSinistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesarSinistreMouseClicked(evt);
            }
        });

        btnCancelarSinistre.setText("Cancelar");
        btnCancelarSinistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarSinistreMouseClicked(evt);
            }
        });

        jLabel10.setText("Perit");

        cboxPerits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxPolices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTancarObrir.setText("Tancar");
        btnTancarObrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTancarObrirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jXDatePickerObertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cboxPolices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jXDatePickerTancament, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jXDatePickerAssignacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboxPerits, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboxTipusSinistre, 0, 140, Short.MAX_VALUE)
                                    .addComponent(cboxEstatSinistre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTancarObrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDesarSinistre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarSinistre)
                                .addGap(4, 4, 4))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cboxTipusSinistre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPolices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePickerObertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxEstatSinistre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jXDatePickerTancament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboxPerits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jXDatePickerAssignacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesarSinistre)
                    .addComponent(btnCancelarSinistre)
                    .addComponent(btnTancarObrir))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarSinistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarSinistreMouseClicked
        parentFrame.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarSinistreMouseClicked

    private void btnDesarSinistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesarSinistreMouseClicked
        if (!taDescripcio.getText().isEmpty()) {
            Sinistre result = creaObjecteSinistre();            
            parentFrame.setEnabled(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Camps marcats en vermell OBLIGATORIS", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDesarSinistreMouseClicked

    private void btnTancarObrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTancarObrirMouseClicked

        tancat = btnTancarObrir.getText().equals("Tancar");
        if (tancat) {
            btnTancarObrir.setText("Obrir");
            cboxEstatSinistre.setSelectedIndex(2);
        } else {
            btnTancarObrir.setText("Tancar");
            if (cboxPerits.getSelectedIndex() == 0) {
                cboxEstatSinistre.setSelectedIndex(0);
            }
            if (cboxPerits.getSelectedIndex() > 0) {
                cboxEstatSinistre.setSelectedIndex(1);
            }
        }
    
    }//GEN-LAST:event_btnTancarObrirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarSinistre;
    private javax.swing.JButton btnDesarSinistre;
    private javax.swing.JButton btnTancarObrir;
    private javax.swing.JComboBox<String> cboxEstatSinistre;
    private javax.swing.JComboBox<String> cboxPerits;
    private javax.swing.JComboBox<String> cboxPolices;
    private javax.swing.JComboBox<String> cboxTipusSinistre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAssignacio;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerObertura;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerTancament;
    private javax.swing.JTextArea taDescripcio;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCorrectly() {
        this.setVisible(true);
        this.setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        cboxTipusSinistre.setModel(new DefaultComboBoxModel(tipusSinistres));
        cboxEstatSinistre.setModel(new DefaultComboBoxModel(estatSinistre));
        jXDatePickerObertura.setDate(new Date());

        perits = dbConnector.getLlistaPerits();
        if (perits != null) {
            List<String> peritNames = new ArrayList<>();
            peritNames.add("No assignat");
            for (Perit p : perits) {
                peritNames.add(p.getPersona().getNom() + " " + p.getPersona().getCognom1());
            }
            cboxPerits.setModel(new DefaultComboBoxModel(peritNames.toArray()));
        } else {
            String[] defaultPerits = new String[]{"No hi ha Perits que mostrar"};
            cboxPerits.setModel(new DefaultComboBoxModel(defaultPerits));
        }
        polices = dbConnector.getLlistaPolices();
        if (polices != null) {
            List<String> polissaIds = new ArrayList<>();
            for (Polissa p : polices) {
                polissaIds.add(String.valueOf(p.getNumero() + " " + p.getTipusHabitatge()));
            }
            cboxPolices.setModel(new DefaultComboBoxModel(polissaIds.toArray()));
        } else {
            String[] defaultPolices = new String[]{"No hi ha Polices que mostrar"};
            cboxPolices.setModel(new DefaultComboBoxModel(defaultPolices));
        }

        cboxPerits.addActionListener(new GestioEstatSinistre());

    }

    private Sinistre creaObjecteSinistre() {
       try {
        Sinistre s = new Sinistre();

        s.setDataObertura(jXDatePickerObertura.getDate());
        s.setDataTancament(jXDatePickerTancament.getDate());
        s.setDataAssignacio(jXDatePickerAssignacio.getDate());

        s.setDescripcio(taDescripcio.getText());
        s.setTipusSinistre(TIPUS_SINISTRE.getTipusFromString(cboxTipusSinistre.getSelectedItem().toString()));
        s.setEstatSinistre(ESTAT_SINISTRE.getEstatSinistreFromString(cboxEstatSinistre.getSelectedItem().toString()));

        if (cboxPerits.getSelectedIndex() == 0) {
            s.setPerit(null);
        } else {
            s.setPerit(perits.get(cboxPerits.getSelectedIndex()-1));
        }
        
        s.setPolissa(polices.get(cboxPolices.getSelectedIndex()));

       
            dbConnector.crearNouSinistre(s);
        } catch (IComponentSGBDException ex) {
            JOptionPane.showMessageDialog(null, "Problemes en enregistrar el Sinistre","ERROR",JOptionPane.ERROR_MESSAGE);
        }

        return null;
    }

    class GestioEstatSinistre implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {            
            if (!cboxPerits.getSelectedItem().toString().equals("No assignat") && !tancat) {
                cboxEstatSinistre.setSelectedIndex(1);
                jXDatePickerAssignacio.setDate(new Date());
            } else if (!tancat) {
                cboxEstatSinistre.setSelectedIndex(0);
                jXDatePickerAssignacio.setDate(null);
            } else if (tancat) {
                cboxEstatSinistre.setSelectedIndex(2);
            }
        }

    }
}

